name: Windoews build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '01 01 * * 6'    # Run every Saturday

jobs:

  list:
    name: list available perl versions
    runs-on: macos-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          print "Version available\n";
          my @versions = perl_versions();
          for my $v (@versions) {
            print "\t$v\n";
          }
          # Don't want anything less then 5.8
          @versions = grep { ! /^5\.6\.*/ } @versions;
          set_output(matrix => {perl => ['latest']});
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run:
    runs-on: macos-latest
    needs: list
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Perl version
        run: perl -V
      # Install liblzma on windows

      - name: Install liblzma
        run: vcpkg install liblzma:x64-windows

      - name: Install dependencies
        # pod::markdown now available in 5.6
        if: matrix.perl != '5.6'
        run: cpanm --quiet --installdeps --notest .

      - name: Build
        run: perl Makefile.PL && make
        env:
          LIBLZMA_INCLUDE: C:\vcpkg\installed\x64-windows\include
          LIBLZMA_LIB: C:\vcpkg\installed\x64-windows\lib

      - name: Test
        run: make test
        env:
          LIBLZMA_INCLUDE: C:\vcpkg\installed\x64-windows\include
          LIBLZMA_LIB: C:\vcpkg\installed\x64-windows\lib
